import { ProviderChakra } from "../providers/Provider"
import ProviderNextAuth from "../providers/ProviderSession"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "BlogOverview",
    description: "Generated by create next app",
};
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ProviderNextAuth>
                    <ProviderChakra>
                        {children}
                    </ProviderChakra>
                </ProviderNextAuth>
            </body>
        </html>
    )
}