import { ProviderChakra } from "../providers/ProviderChakra"
import ProviderNextAuth from "../providers/ProviderSession"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Flex } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "BlogOverview",
    description: "Generated by create next app",
};
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ProviderNextAuth>
                    <ProviderChakra>
                        <Flex minHeight='100vh' flexDirection='column' alignItems='center' justifyContent='center' bg='whitesmoke'>
                            {children}
                        </Flex>
                    </ProviderChakra>
                </ProviderNextAuth>
            </body>
        </html>
    )
}