import { Navegation } from "@/features/ui/index"
import { ProviderChakra } from "../providers/Provider"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata:Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ProviderChakra>
          <Navegation></Navegation>
          {children}
        </ProviderChakra>
      </body>
    </html>
  )
}
