import { ProviderChakra } from "../providers/Provider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ProviderChakra>
          {children}
        </ProviderChakra>
      </body>
    </html>
  )
}
