import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ProviderChakra } from "../providers/Provider";
import { Navegation } from "@/features/ui/index";
import ProviderNextAuth from "../providers/ProviderSession";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BlogOverview",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderNextAuth>
          <ProviderChakra>
            <Navegation />
            {children}
          </ProviderChakra>
        </ProviderNextAuth>
      </body>
    </html>
  );
}
